### ISSUE TITLE
New major conda-lock release incoming

### ISSUE THREAD

**Issue by maresb** [basnijholt/unidep#194]
Hey @basnijholt! I still have a few more minor todos, but I'm hoping to release conda-lock v3 very soon. Would you be able to test `main` and make sure everything works smoothly for you? Thanks!

**Comment by basnijholt** [comment]
Cool! And thanks for letting me know here. I will definitely try it out.

**Comment by basnijholt** [comment]
Everything still seems to work!

From inspecting diffs from a 20k line resulting conda-lock file, it seems that only the sorting order of the `dependencies:` dict is now different.

Looking forward to v3!

I also saw some PRs regarding pixi. I am thinking about making `unidep` pixi compatible too. Such that one can have one requirements file that would work for just pip, conda, and pixi.
