### ISSUE TITLE
unidep merge -d . command does not detect pyproject.toml in project directory on Apple Silicon Mac running MacOS 15.1

### ISSUE THREAD

**Issue by nickpowersys** [basnijholt/unidep#208]
I installed `unidep` on my M1 Mac and ran the command `unidep merge -d .`.

Although there is a `pyproject.toml` file in the working (project root) directory, the error message is

`No `requirements.yaml` or `pyproject.toml` files found in .`.

I also tried it with `--directory` in place of `-d` and got the same result.

**Comment by basnijholt** [comment]
Thanks for reporting!

What is the content of pyproject.toml?

Does it have the unidep sections?

**Comment by nickpowersys** [comment]
I was using the current `pyrproject.toml` from the UniDep repo, as of Oct. 5, 2024, commit 24ac2e7a.

I did not realize a `[tool.unidep]` section was needed. When I re-ran the command after using the `[tool.unidep] dependencies` section from the UniDep example, it generated an `environment.yaml` file.

Is there a way to have the `merge` command use existing `pyproject.toml [project]` dependencies sections?

**Comment by basnijholt** [comment]
No unfortunately not. The main reason being that the names of packages on PyPI and Conda aren't always the same.

**Comment by nickpowersys** [comment]
Thanks for explaining. I am glad to have found the tool. It can help projects support the use of either type of package, as well as a mixture of both.

**Comment by nickpowersys** [comment]
Closing.
